import {defineArrayMember, defineField, defineType} from 'sanity'

export const articleType = defineType({
  name: 'article',
  title: 'Article',
  type: 'document',
  groups: [
    {name: 'content', title: 'Content', default: true},
    {name: 'workflow', title: 'Workflow'},
    {name: 'seo', title: 'SEO'},
    {name: 'social', title: 'Social'},
    {name: 'relationships', title: 'Relationships'},
  ],
  fields: [
    defineField({name: 'title', title: 'Editorial title', type: 'string', group: 'content', validation: (rule) => rule.required().max(100)}),
    defineField({
      name: 'slug',
      title: 'URL slug',
      type: 'slug',
      group: 'content',
      options: {source: 'title', maxLength: 96},
      validation: (rule) => rule.required(),
    }),
    defineField({name: 'description', title: 'Description / deck', type: 'text', rows: 3, group: 'content', validation: (rule) => rule.required().max(240)}),
    defineField({name: 'publishedAt', title: 'Publication date', type: 'datetime', group: 'content', validation: (rule) => rule.required()}),
    defineField({name: 'updatedAt', title: 'Substantive update date', type: 'datetime', group: 'content'}),
    defineField({
      name: 'author',
      title: 'Author',
      type: 'reference',
      to: [{type: 'author'}],
      group: 'content',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'category',
      title: 'Category',
      type: 'reference',
      to: [{type: 'category'}],
      group: 'content',
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: 'featuredImage',
      title: 'Featured image',
      type: 'image',
      options: {hotspot: true},
      group: 'content',
      fields: [
        defineField({name: 'alt', title: 'Alternative text', type: 'string', validation: (rule) => rule.required()}),
        defineField({name: 'caption', title: 'Caption', type: 'string'}),
      ],
      validation: (rule) => rule.required(),
    }),
    defineField({name: 'body', title: 'Article body', type: 'blockContent', group: 'content', validation: (rule) => rule.required()}),
    defineField({
      name: 'pillarArticle',
      title: 'Supporting pillar article',
      description: 'The primary article this supporting article strengthens and links back to.',
      type: 'reference',
      to: [{type: 'article'}],
      group: 'relationships',
    }),
    defineField({name: 'primaryKeyword', title: 'Primary keyword', type: 'string', group: 'workflow'}),
    defineField({name: 'secondaryKeywords', title: 'Secondary keywords', type: 'array', of: [{type: 'string'}], group: 'workflow'}),
    defineField({
      name: 'reviewStatus',
      title: 'Editorial status',
      type: 'string',
      group: 'workflow',
      initialValue: 'needsReview',
      options: {
        layout: 'radio',
        list: [
          {title: 'Needs review', value: 'needsReview'},
          {title: 'Changes requested', value: 'changesRequested'},
          {title: 'Approved', value: 'approved'},
        ],
      },
    }),
    defineField({
      name: 'editorialAssessment',
      title: 'Editorial assessment',
      type: 'object',
      group: 'workflow',
      fields: [
        defineField({name: 'score', title: 'Overall score', type: 'number', validation: (rule) => rule.min(0).max(100)}),
        defineField({name: 'summary', title: 'Review summary', type: 'text', rows: 3}),
        defineField({name: 'flags', title: 'Items to verify', type: 'array', of: [{type: 'string'}]}),
      ],
    }),
    defineField({
      name: 'contentProvenance',
      title: 'Content provenance',
      type: 'object',
      group: 'workflow',
      readOnly: true,
      fields: [
        defineField({name: 'source', title: 'Source', type: 'string'}),
        defineField({name: 'sourceId', title: 'Source article ID', type: 'string'}),
        defineField({name: 'sourceUrl', title: 'Source URL', type: 'url'}),
        defineField({name: 'sourceScore', title: 'Source score', type: 'number'}),
        defineField({name: 'receivedAt', title: 'Received at', type: 'datetime'}),
        defineField({name: 'inputFingerprint', title: 'Input fingerprint', type: 'string'}),
        defineField({name: 'processorModel', title: 'Processor model', type: 'string'}),
      ],
    }),
    defineField({
      name: 'sources',
      title: 'Sources and further reading',
      type: 'array',
      group: 'content',
      of: [
        defineArrayMember({
          type: 'object',
          name: 'source',
          fields: [
            defineField({name: 'title', title: 'Title', type: 'string', validation: (rule) => rule.required()}),
            defineField({name: 'publisher', title: 'Publisher / author', type: 'string'}),
            defineField({name: 'url', title: 'URL', type: 'url'}),
            defineField({name: 'publishedAt', title: 'Publication date', type: 'date'}),
          ],
          preview: {select: {title: 'title', subtitle: 'publisher'}},
        }),
      ],
    }),
    defineField({name: 'seoTitle', title: 'SEO title', type: 'string', group: 'seo', description: 'Defaults to the editorial title.', validation: (rule) => rule.max(65)}),
    defineField({name: 'metaDescription', title: 'Meta description', type: 'text', rows: 3, group: 'seo', description: 'Defaults to the article description.', validation: (rule) => rule.max(170)}),
    defineField({name: 'canonicalUrl', title: 'Canonical URL override', type: 'url', group: 'seo'}),
    defineField({name: 'noIndex', title: 'Exclude from search engines', type: 'boolean', group: 'seo', initialValue: false}),
    defineField({name: 'socialTitle', title: 'Social title', type: 'string', group: 'social'}),
    defineField({name: 'socialDescription', title: 'Social description', type: 'text', rows: 3, group: 'social'}),
    defineField({name: 'socialImage', title: 'Social image override', type: 'image', options: {hotspot: true}, group: 'social'}),
    defineField({name: 'linkedInCopy', title: 'LinkedIn post copy', type: 'text', rows: 8, group: 'social'}),
    defineField({name: 'facebookInstagramCopy', title: 'Facebook / Instagram caption', type: 'text', rows: 8, group: 'social'}),
    defineField({name: 'xCopy', title: 'X post copy', type: 'text', rows: 5, group: 'social', validation: (rule) => rule.max(280)}),
    defineField({name: 'hashtags', title: 'Suggested hashtags', type: 'array', of: [{type: 'string'}], group: 'social'}),
    defineField({name: 'featured', title: 'Feature on Insights page', type: 'boolean', group: 'relationships', initialValue: false}),
    defineField({name: 'relatedArticles', title: 'Related articles', type: 'array', of: [{type: 'reference', to: [{type: 'article'}]}], group: 'relationships', validation: (rule) => rule.max(3)}),
    defineField({
      name: 'cta',
      title: 'Article CTA',
      type: 'object',
      group: 'relationships',
      fields: [
        defineField({name: 'eyebrow', title: 'Eyebrow', type: 'string'}),
        defineField({name: 'title', title: 'Title', type: 'string'}),
        defineField({name: 'body', title: 'Body', type: 'text', rows: 3}),
        defineField({name: 'buttonLabel', title: 'Button label', type: 'string'}),
        defineField({name: 'buttonHref', title: 'Button URL', type: 'string'}),
      ],
    }),
  ],
  orderings: [
    {title: 'Publication date, newest', name: 'publishedAtDesc', by: [{field: 'publishedAt', direction: 'desc'}]},
  ],
  preview: {
    select: {title: 'title', subtitle: 'author.name', media: 'featuredImage'},
  },
})
